<x-admin.layout title="Import JSON">
    <x-admin.page-header title="Import JSON" subtitle="Bring in pages, sections, blocks or templates written by hand, exported from another PACMS site, or generated by an AI assistant. Imports always become drafts.">
        <x-slot:actions>
            <a href="{{ route('admin.import.schema') }}" class="btn btn-outline-secondary"><i class="bi bi-download" aria-hidden="true"></i> JSON Schema</a>
        </x-slot:actions>
    </x-admin.page-header>

    <div class="row g-4">
        <div class="col-xl-7">
            <form method="POST" action="{{ route('admin.import.store') }}" enctype="multipart/form-data" class="card pa-card" novalidate>
                @csrf
                <div class="card-header"><h2 class="h6 mb-0">1. Paste or upload</h2></div>
                <div class="card-body">
                    <x-admin.field name="json" label="JSON" type="textarea" rows="14" class="font-monospace small" help="The whole document, starting with { and including &quot;schema_version&quot;: &quot;1.0&quot;. Code-like content is never run; it is removed and reported." />
                    <div class="mb-3">
                        <label for="field-file" class="form-label">…or a .json file (max 2 MB)</label>
                        <input id="field-file" type="file" name="file" accept=".json,application/json" class="form-control @error('file') is-invalid @enderror">
                        @error('file')<div class="invalid-feedback">{{ $message }}</div>@enderror
                    </div>
                    <button type="submit" class="btn btn-primary">Check the document</button>
                    <p class="form-text mb-0">Nothing is created yet: you see a report and a preview first.</p>
                </div>
            </form>

            <section class="card pa-card mt-4" aria-labelledby="recent-imports">
                <div class="card-header"><h2 id="recent-imports" class="h6 mb-0">Your recent imports</h2></div>
                @if ($jobs->isEmpty())
                    <div class="card-body small text-body-secondary">None yet.</div>
                @else
                    <ul class="list-group list-group-flush">
                        @foreach ($jobs as $job)
                            <li class="list-group-item d-flex justify-content-between align-items-center gap-2">
                                <span>
                                    <a href="{{ route('admin.import.show', $job) }}">{{ $job->title ?: ucfirst($job->kind).' import' }}</a>
                                    <span class="small text-body-secondary">· {{ $job->kind }} · {{ $job->created_at?->diffForHumans() }}</span>
                                </span>
                                <x-admin.import-status :job="$job" />
                            </li>
                        @endforeach
                    </ul>
                @endif
            </section>
        </div>

        <div class="col-xl-5">
            <section class="card pa-card" aria-labelledby="ai-helper">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h2 id="ai-helper" class="h6 mb-0">Working with an AI assistant</h2>
                    <button type="button" class="btn btn-sm btn-outline-primary" data-copy-target="#ai-prompt"><i class="bi bi-clipboard" aria-hidden="true"></i> Copy</button>
                </div>
                <div class="card-body">
                    <p class="small">Paste these instructions into ChatGPT, Claude or Gemini, then ask for the page you want (“an About us page with our history, team photo and a contact button”). Paste the answer on the left.</p>
                    <label for="ai-prompt" class="visually-hidden">Instructions for an AI assistant</label>
                    <textarea id="ai-prompt" class="form-control font-monospace small" rows="18" readonly>{{ $prompt }}</textarea>
                    <p class="form-text mb-0">The list of block types is generated from this site, so it includes your custom blocks.</p>
                </div>
            </section>
        </div>
    </div>
</x-admin.layout>
